"""initial migration

Revision ID: 95458f9ba1d0
Revises: 
Create Date: 2025-11-05 15:57:12.752026

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "95458f9ba1d0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_password_reset_tokens_code", table_name="password_reset_tokens")
    op.drop_index("ix_password_reset_tokens_token", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.add_column("reports", sa.Column("service_request_id", sa.UUID(), nullable=False))
    op.add_column("reports", sa.Column("applicant_id", sa.UUID(), nullable=False))
    op.add_column("reports", sa.Column("current_version", sa.Integer(), nullable=True))
    op.drop_constraint("reports_id_key", "reports", type_="unique")
    op.drop_constraint("reports_application_id_fkey", "reports", type_="foreignkey")
    op.create_foreign_key(
        None, "reports", "service_requests", ["service_request_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "reports", "applicants", ["applicant_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("reports", "finalized_at")
    op.drop_column("reports", "created_at")
    op.drop_column("reports", "overall_result")
    op.drop_column("reports", "status")
    op.drop_column("reports", "version")
    op.drop_column("reports", "application_id")
    op.alter_column(
        "users",
        "last_login",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "last_activity",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "locked_until",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "locked_until",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "last_activity",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "last_login",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.add_column(
        "reports", sa.Column("application_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column("reports", sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "reports",
        sa.Column(
            "status",
            postgresql.ENUM("DRAFT", "GENERATED", "REVIEWED", "FINALIZED", name="reportstatus"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "reports",
        sa.Column("overall_result", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.add_column(
        "reports",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "reports",
        sa.Column("finalized_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "reports", type_="foreignkey")
    op.drop_constraint(None, "reports", type_="foreignkey")
    op.create_foreign_key(
        "reports_application_id_fkey",
        "reports",
        "applicants",
        ["application_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("reports_id_key", "reports", ["id"])
    op.drop_column("reports", "current_version")
    op.drop_column("reports", "applicant_id")
    op.drop_column("reports", "service_request_id")
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("code", sa.VARCHAR(length=6), autoincrement=False, nullable=False),
        sa.Column("token", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("is_used", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column("user_agent", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("used_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="password_reset_tokens_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="password_reset_tokens_pkey"),
    )
    op.create_index(
        "ix_password_reset_tokens_token", "password_reset_tokens", ["token"], unique=False
    )
    op.create_index(
        "ix_password_reset_tokens_code", "password_reset_tokens", ["code"], unique=False
    )
    # ### end Alembic commands ###
