"""Change id

Revision ID: a6a06cdb042c
Revises: fdd58e4a2a58
Create Date: 2025-11-07 10:35:08.060886

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a6a06cdb042c"
down_revision = "fdd58e4a2a58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_password_reset_tokens_code", table_name="password_reset_tokens")
    op.drop_index("ix_password_reset_tokens_token", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.alter_column(
        "notifications",
        "resource_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="resource_id::text::uuid",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "notifications",
        "resource_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        postgresql_using="resource_id::text::integer",
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("code", sa.VARCHAR(length=6), autoincrement=False, nullable=False),
        sa.Column("token", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("is_used", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column("user_agent", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("used_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="password_reset_tokens_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="password_reset_tokens_pkey"),
    )
    op.create_index(
        "ix_password_reset_tokens_token", "password_reset_tokens", ["token"], unique=False
    )
    op.create_index(
        "ix_password_reset_tokens_code", "password_reset_tokens", ["code"], unique=False
    )
    # ### end Alembic commands ###
