"""Consolidate all model changes

Revision ID: b032f2683d32
Revises: 
Create Date: 2025-11-06 09:23:10.665094

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b032f2683d32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop FKs referencing applications before dropping the table to avoid dependency errors
    op.drop_constraint('tasks_application_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('documents_application_id_fkey', 'documents', type_='foreignkey')
    op.drop_constraint('background_checks_application_id_fkey', 'background_checks', type_='foreignkey')
    op.drop_constraint('reports_application_id_fkey', 'reports', type_='foreignkey')

    op.drop_index('ix_applications_reference_number', table_name='applications')
    op.drop_table('applications')

    op.drop_index('ix_password_reset_tokens_code', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_token', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.create_unique_constraint(None, 'audit_logs', ['id'])
    op.create_unique_constraint(None, 'background_checks', ['id'])
    op.create_foreign_key(None, 'background_checks', 'applicants', ['application_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'clients', ['id'])
    op.create_unique_constraint(None, 'documents', ['id'])
    op.create_foreign_key(None, 'documents', 'applicants', ['application_id'], ['id'], ondelete='CASCADE')
    op.add_column('invitations', sa.Column('invitation_type', sa.String(length=20), nullable=False))
    op.add_column('invitations', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'invitations', ['id'])
    op.create_unique_constraint(None, 'notifications', ['id'])
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.add_column('reports', sa.Column('service_request_id', sa.UUID(), nullable=False))
    op.add_column('reports', sa.Column('applicant_id', sa.UUID(), nullable=False))
    op.add_column('reports', sa.Column('current_version', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reports', 'service_requests', ['service_request_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reports', 'applicants', ['applicant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reports', 'application_id')
    op.drop_column('reports', 'overall_result')
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'version')
    op.drop_column('reports', 'finalized_at')
    op.drop_column('reports', 'created_at')
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'task_activities', ['id'])
    op.create_unique_constraint(None, 'task_comments', ['id'])
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.create_foreign_key(None, 'tasks', 'applicants', ['application_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_application_id_fkey', 'tasks', 'applications', ['application_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'task_comments', type_='unique')
    op.drop_constraint(None, 'task_activities', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.add_column('reports', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('finalized_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('status', postgresql.ENUM('DRAFT', 'GENERATED', 'REVIEWED', 'FINALIZED', name='reportstatus'), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('overall_result', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_application_id_fkey', 'reports', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reports', 'current_version')
    op.drop_column('reports', 'applicant_id')
    op.drop_column('reports', 'service_request_id')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_constraint(None, 'invitations', type_='unique')
    op.drop_column('invitations', 'company_name')
    op.drop_column('invitations', 'invitation_type')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_application_id_fkey', 'documents', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'background_checks', type_='foreignkey')
    op.create_foreign_key('background_checks_application_id_fkey', 'background_checks', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'background_checks', type_='unique')
    op.drop_constraint(None, 'audit_logs', type_='unique')
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='password_reset_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='password_reset_tokens_pkey')
    )
    op.create_index('ix_password_reset_tokens_token', 'password_reset_tokens', ['token'], unique=False)
    op.create_index('ix_password_reset_tokens_code', 'password_reset_tokens', ['code'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('applicant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ghana_card_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('permanent_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permanent_address_gps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_address_gps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('employment_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('education_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'IN_PROGRESS', 'UNDER_REVIEW', 'COMPLETED', 'CANCELLED', name='applicationstatus'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], name='applications_applicant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name='applications_assigned_to_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='applications_client_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='applications_pkey')
    )
    op.create_index('ix_applications_reference_number', 'applications', ['reference_number'], unique=False)
    # ### end Alembic commands ###
