"""Set all datetime to timezone-aware

Revision ID: f1abe203b870
Revises: 23d210c7c34f
Create Date: 2025-11-06 12:07:13.197622

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f1abe203b870"
down_revision = "23d210c7c34f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_password_reset_tokens_code", table_name="password_reset_tokens")
    op.drop_index("ix_password_reset_tokens_token", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.alter_column(
        "service_request_applicants",
        "added_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "service_request_applicants",
        "added_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("code", sa.VARCHAR(length=6), autoincrement=False, nullable=False),
        sa.Column("token", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("is_used", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column("user_agent", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("used_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="password_reset_tokens_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="password_reset_tokens_pkey"),
    )
    op.create_index(
        "ix_password_reset_tokens_token", "password_reset_tokens", ["token"], unique=False
    )
    op.create_index(
        "ix_password_reset_tokens_code", "password_reset_tokens", ["code"], unique=False
    )
    # ### end Alembic commands ###
