"""Change address fields to JSON

Revision ID: fdd58e4a2a58
Revises: f1abe203b870
Create Date: 2025-11-06 16:21:04.040860

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "fdd58e4a2a58"
down_revision = "f1abe203b870"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_password_reset_tokens_code", table_name="password_reset_tokens")
    op.drop_index("ix_password_reset_tokens_token", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.alter_column(
        "personal_details",
        "current_res_add",
        existing_type=sa.VARCHAR(length=255),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="current_res_add::json",
    )
    op.alter_column(
        "personal_details",
        "permanent_res_add",
        existing_type=sa.VARCHAR(length=255),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="permanent_res_add::json",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "personal_details",
        "permanent_res_add",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "personal_details",
        "current_res_add",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("code", sa.VARCHAR(length=6), autoincrement=False, nullable=False),
        sa.Column("token", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("is_used", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column("user_agent", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("used_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="password_reset_tokens_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="password_reset_tokens_pkey"),
    )
    op.create_index(
        "ix_password_reset_tokens_token", "password_reset_tokens", ["token"], unique=False
    )
    op.create_index(
        "ix_password_reset_tokens_code", "password_reset_tokens", ["code"], unique=False
    )
    # ### end Alembic commands ###
